""" plugins
source ~/.dotfiles/vim/minpac.vim

""" options
set encoding=utf-8
set nobackup
set nowritebackup
set noswapfile
set showcmd " display incomplete commands
set showmode " display mode below statusline
set autowrite " automatically :write before running commands
set shiftround " use multiple of shiftwidth when indenting
set list listchars=tab:»·,trail:·,nbsp:· " display extra whitespace
set nojoinspaces " use one space after punctuation
set textwidth=80
set colorcolumn=+1
set scrolloff=5 " keep at least 5 lines when scrolling
set number
set relativenumber " number lines relative to current one
" open splits below and right
set splitbelow
set splitright
set hlsearch " highlight search results
set showmatch " highlight matching parenthesis
set cursorline " highlight current line
set spelllang=en_us " set spellchecking locale
set wildmenu
set wildmode=longest:full,full " expand to the longest match, then show wildmenu

""" theme
colorscheme zenburn

""" mappings
let mapleader="," " set <leader> key to <,>
" fugitive
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gp :Gpull<CR>
nnoremap <leader>gu :Gpush<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>gl :Glog<CR>
nnoremap <leader>gb :Gblame<CR>

""" plugins
" grep
if executable("rg")
  set grepprg=rg\ --vimgrep
  set grepformat^=%f:%l:%c:%m
endif
" ale
let g:ale_sign_column_always = 1

""" statusline
source ~/.dotfiles/vim/statusline.vim
