### Antigen ###
source ~/.dotfiles/vendor/antigen/bin/antigen.zsh
# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting
# Completions bundle
antigen bundle zsh-users/zsh-completions
# Tell Antigen that you're done.
antigen apply
### Antigen ###

### Theme ###
source ~/.dotfiles/zsh/clean.zsh-theme
### Theme ###

### Functions ###
source ~/.dotfiles/zsh/functions.sh
### Functions ###

### Variables ###
# The current user is the default user
DEFAULT_USER="$(whoami)"
export DEFAULT_USER
# Enable CLI colors
case "$(uname)" in
  "Darwin")
    export CLICOLOR=1
    ;;
  "Linux")
    alias ls='ls --color=auto'
    ;;
esac
# Use vim as the default editor
export EDITOR="vim"
GPG_TTY="$(tty)"
export GPG_TTY
TMUX_SHELL="$(command -v zsh)"
export TMUX_SHELL
### Variables ###

### Ruby ###
# Set up rbenv
eval "$(rbenv init -)"
### Ruby ###

### Python ###
# Set up pyenv
eval "$(pyenv init -)"
### Python ###
