### Antigen ###
source ~/.dotfiles/vendor/antigen/bin/antigen.zsh
# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting
# Completions bundle
antigen bundle zsh-users/zsh-completions
# Tell Antigen that you're done.
antigen apply
### Antigen ###

### Theme ###
source ~/.dotfiles/zsh/clean.zsh-theme
### Theme ###

### Variables ###
# The current user is the default user
export DEFAULT_USER=$(whoami)
# Enable CLI colors
case $OSTYPE in
  "darwin"*)
    export CLICOLOR=1
    ;;
  "linux-gnu")
    alias ls='ls --color=auto'
    ;;
esac
# Use vim as the default editor
export EDITOR=vim
export GPG_TTY=$(tty)
export TMUX_SHELL=$(command -v zsh)
### Variables ###

### Ruby ###
# Set up rbenv
eval "$(rbenv init -)"
### Ruby ###

### Python ###
# Set up pyenv
eval "$(pyenv init -)"
### Python ###
